### ISSUE TITLE
Mac (OS X 10.14.1) crash on start.

### ISSUE THREAD

**Issue by Number16BusShelter** [Conky-for-macOS/Manage-Conky#18]
Got this report:
```Path:                  /Volumes/VOLUME/Manage Conky.app/Contents/MacOS/Manage Conky
Identifier:            org.npyl.Manage-Conky
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Manage Conky [51250]
User ID:               

Date/Time:           
OS Version:            Mac OS X 10.14.1 (18B75)
Report Version:        12
Bridge OS Version:    
Anonymous UUID:        

Sleep/Wake UUID:      

Time Awake Since Boot: 24000 seconds
Time Since Wake:       16000 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010b1ae000-000000010b1c9000 [  108K] r-x/rwx SM=COW  

Thread 0 Crashed:
0                                 	0x000000011ac0b000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee4a51b88
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000011ac0b000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x10b1ae000 -        0x10b1c8fff + (0) <AD80F0A9-B94A-3516-B763-3E64EA8C759C> 
       0x11ac0a000 -        0x11ac886a7 + (635.2) <1780094A-8FE2-3EAA-B4A3-C4CF14BC5196> 

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 24505
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=888K resident=0K(0%) swapped_out_or_unallocated=888K(100%)
Writable regions: Total=8400K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8400K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
__DATA                             272K        4 
__LINKEDIT                         272K        3 
__TEXT                             616K        3 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                             65.1M       11 ```

**Comment by Number16BusShelter** [comment]
Mac OS X 10.14.2 is out. I will install it and try to reproduce the behavior.

**Comment by Number16BusShelter** [comment]
Nope, didn't help

**Comment by Number16BusShelter** [comment]
Also I'd like to mention that I had to
```
sudo xattr -rd com.apple.quarantine /Applications/[LockedApp].app
```

> To resolute Gatekeeper issues on macOS Sierra you might have to partially or completely disable Gatekeeper checks.

[https://apple.stackexchange.com/questions/262355/xxx-cant-be-opened-you-should-move-it-to-trash-for-flash-projector-applicat](Issue link)

Because mac returned this type of error "**... can't be opened. You should move it to trash**" while installing the app.

I'd like to point out that I did not install **cinky** or **cinky-manager** from _source_.

But as far as I've already tried to build cinky locally and failed I hope your **.dmg transports and installs _cinky_**.

**Comment by npyl** [comment]
Trying to build locally should basically fail, because it is trying to find my Mac Developer identity.
If you got to Xcode, and remove it from every project (ManageConky, and ConkyX) you should be able to build it.

Use the script called `DistributeManageConky.command` in Tools folder. ;)

**Comment by npyl** [comment]
I really can't find a way to get an Apple Developer's license without having to pay the 99USD fee annually.  I don't really see the point in paying it since I am not willing to sell any of my apps. 

This is so messed up. 🤔

**Comment by sanktis** [comment]
Hm got the same issu here. I cant open the dmg over UI so i opened it over terminal. So i was able to move the app to the application folder. But at startup of the app i get the same error. Manage Conky quit unexpectedly.
Im able to open the apps contend but not able to start. The trick with sudo xattr -rd com.apple.quarantine /Applications/[LockedApp].app or disable the gatekeeper in general does also not work.

**Comment by npyl** [comment]
@sanktis I will upload a new dmg really soon which I think will work.  Also, it will have some cool new features.

Stay tuned.  Thanks for the support.

**Comment by npyl** [comment]
Does this dmg work?

[Manage Conky_v0.9.5.zip](https://github.com/Conky-for-macOS/Manage-Conky/files/2721146/Manage.Conky_v0.9.5.zip)

**Comment by sanktis** [comment]
Hi Sorry for the delay

Yes the dmg is mountable and the app is starting correctly!
Thanks many for your effort!

Happy new Year

**Comment by npyl** [comment]
@sanktis Thanks for testing! :)

If it works for one, it should work for all.

Happy new year to everyone (@sanktis  @Number16BusShelter  @hajo62)
