### ISSUE TITLE
How I can uninstall Conky?

### ISSUE THREAD

**Issue by barra51** [Conky-for-macOS/Manage-Conky#20]
Hi to all,
How can I full remove Conky from my system? I just click on remove Conky from the application menu, but I can see process running from my sistem:

ps aux | grep -i conky 
Miguel          30132   0.0  0.0  2442952    396 s000  R+   11:30PM   0:00.00 grep -i conky
Miguel          30103   0.0  0.0  2434408    564   ??  S    11:30PM   0:00.00 /bin/bash -l -c /usr/local/bin/conky -c /Users/Miguel/Documents/Conky/npyl-theme/CPU\ Panel\ \(4-core\)
Miguel          30100   0.0  0.1  2436456   1156   ??  S    11:30PM   0:00.01 /bin/bash -l -c /usr/local/bin/conky -c /Users/Miguel/Documents/Conky/npyl-theme/CPU\ Panel\ \(4-core\)
Miguel          29417   0.0  0.1  2444648   1272   ??  S    11:30PM   0:00.06 /bin/bash -l -c /usr/local/bin/conky -c /Users/Miguel/Documents/Conky/npyl-theme/Gotham

**Comment by npyl** [comment]
Hi!
I suspect that ManageConky doesn't close conky before uninstalling which means that although uninstalled, conky is still in memory.

Some ways to know for sure:
`ls -l /Applications | grep Conky`
`ls -l /usr/local/bin | grep conky`

If any of these commands gives an output, it means that conky was indeed not uninstalled.

**Comment by npyl** [comment]
I have issued a bugfix that will be available when I release version 1.0.
