### ISSUE TITLE
Error on installing

### ISSUE THREAD

**Issue by DenisBopp** [Conky-for-macOS/Manage-Conky#5]
Hey, its me again, I try to install but get this now?

Dyld Error Message:
  Library not loaded: @rpath/HomebrewCtl.framework/Versions/A/HomebrewCtl
  Referenced from: /private/var/folders/*/Manage Conky.app/Contents/MacOS/Manage Conky
  Reason: image not found

but I have brew installed!

**Comment by npyl** [comment]
Hi! I was afraid this was going to happen! I uploaded [ManageConky](https://github.com/Conky-for-macOS/Manage-Conky/releases/tag/v0.7) again!

**Comment by npyl** [comment]
To begin the installation process open ManageConky, click Conky Preferences and hit the Install button! Thats it!
